1)Загрузите датасет для регрессии, выделите целевой признак и предикторы, разбейте данные на обучающую и тестовую выборку;

In [ ]:
#загрузите датасет для регрессии
import pandas as pd
from scipy.stats import *
data = pd.read_csv('/content/diamonds.csv')
data.drop(['Unnamed: 0'], axis=1, inplace=True)
data

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [ ]:
data.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [ ]:
data = pd.get_dummies(data, columns=['cut','color','clarity'])
data

carat  depth  table  price     x     y     z  cut_Fair  cut_Good  \
0       0.23   61.5   55.0    326  3.95  3.98  2.43         0         0   
1       0.21   59.8   61.0    326  3.89  3.84  2.31         0         0   
2       0.23   56.9   65.0    327  4.05  4.07  2.31         0         1   
3       0.29   62.4   58.0    334  4.20  4.23  2.63         0         0   
4       0.31   63.3   58.0    335  4.34  4.35  2.75         0         1   
...      ...    ...    ...    ...   ...   ...   ...       ...       ...   
53935   0.72   60.8   57.0   2757  5.75  5.76  3.50         0         0   
53936   0.72   63.1   55.0   2757  5.69  5.75  3.61         0         1   
53937   0.70   62.8   60.0   2757  5.66  5.68  3.56         0         0   
53938   0.86   61.0   58.0   2757  6.15  6.12  3.74         0         0   
53939   0.75   62.2   55.0   2757  5.83  5.87  3.64         0         0   

       cut_Ideal  ...  color_I  color_J  clarity_I1  clarity_IF  clarity_SI1  \
0              1  ...        0        0           0           0            0   
1              0  ...        0        0           0           0            1   
2              0  ...        0        0           0           0            0   
3              0  ...        1        0           0           0            0   
4              0  ...        0        1           0           0            0   
...          ...  ...      ...      ...         ...         ...          ...   
53935          1  ...        0        0           0           0            1   
53936          0  ...        0        0           0           0            1   
53937          0  ...        0        0           0           0            1   
53938          0  ...        0        0           0           0            0   
53939          1  ...        0        0           0           0            0   

       clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  clarity_VVS2  
0                1            0            0             0             0  
1                0            0            0             0             0  
2                0            1            0             0             0  
3                0            0            1             0             0  
4                1            0            0             0             0  
...            ...          ...          ...           ...           ...  
53935            0            0            0             0             0  
53936            0            0            0             0             0  
53937            0            0            0             0             0  
53938            1            0            0             0             0  
53939            1            0            0             0             0  

[53940 rows x 27 columns]

In [ ]:
y = data["price"]
X = data.drop(["price"], axis=1)

In [ ]:
y

0         326
1         326
2         327
3         334
4         335
         ... 
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64

In [ ]:
X

carat  depth  table     x     y     z  cut_Fair  cut_Good  cut_Ideal  \
0       0.23   61.5   55.0  3.95  3.98  2.43         0         0          1   
1       0.21   59.8   61.0  3.89  3.84  2.31         0         0          0   
2       0.23   56.9   65.0  4.05  4.07  2.31         0         1          0   
3       0.29   62.4   58.0  4.20  4.23  2.63         0         0          0   
4       0.31   63.3   58.0  4.34  4.35  2.75         0         1          0   
...      ...    ...    ...   ...   ...   ...       ...       ...        ...   
53935   0.72   60.8   57.0  5.75  5.76  3.50         0         0          1   
53936   0.72   63.1   55.0  5.69  5.75  3.61         0         1          0   
53937   0.70   62.8   60.0  5.66  5.68  3.56         0         0          0   
53938   0.86   61.0   58.0  6.15  6.12  3.74         0         0          0   
53939   0.75   62.2   55.0  5.83  5.87  3.64         0         0          1   

       cut_Premium  ...  color_I  color_J  clarity_I1  clarity_IF  \
0                0  ...        0        0           0           0   
1                1  ...        0        0           0           0   
2                0  ...        0        0           0           0   
3                1  ...        1        0           0           0   
4                0  ...        0        1           0           0   
...            ...  ...      ...      ...         ...         ...   
53935            0  ...        0        0           0           0   
53936            0  ...        0        0           0           0   
53937            0  ...        0        0           0           0   
53938            1  ...        0        0           0           0   
53939            0  ...        0        0           0           0   

       clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
0                0            1            0            0             0   
1                1            0            0            0             0   
2                0            0            1            0             0   
3                0            0            0            1             0   
4                0            1            0            0             0   
...            ...          ...          ...          ...           ...   
53935            1            0            0            0             0   
53936            1            0            0            0             0   
53937            1            0            0            0             0   
53938            0            1            0            0             0   
53939            0            1            0            0             0   

       clarity_VVS2  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
...             ...  
53935             0  
53936             0  
53937             0  
53938             0  
53939             0  

[53940 rows x 26 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((43152, 26), (43152,), (10788, 26), (10788,))

2)Решите задачу регрессии на ваших данных с использованием моделей sklearn (линейная регрессия + L1, L2), для моделей с регуляризациями подберите гиперпараметр;

In [ ]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
lr = LinearRegression().fit(X_train, y_train)
lr.predict(X_test)

array([  895.36253225, 11164.627689  ,   762.24228366, ...,
        8634.79084302, 10164.3482269 ,  2233.13007942])

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from math import sqrt

y_pred = lr.predict(X_test)

#средняя абсолютная ошибка (Mean Absolute Error, MAE)
#средняя квадратичная ошибка (Mean Squared Error, MSE)
#квадратный корень из средней квадратичной ошибки (Root Mean Squared Error)
#средняя абсолютная ошибка в процентах (Mean Absolute Percentage Error, MAPE)
#коэффициент детерминации R^2

print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
print(f'R^2: {lr.score(X_test, y_test)}')

MAE: 742.3775742231418
MSE: 1348616.276348747
RMSE: 1161.299391349512
MAPE: 0.6195329525520882
R^2: 0.9176947879258784


In [ ]:
lasso = Lasso(alpha=0.0).fit(X_train, y_train)
y_pred = lasso.predict(X_test)
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
print(f'R^2: {lasso.score(X_test, y_test)}')
lasso.coef_

<ipython-input-92-3d83e1c15e0e>:1: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  lasso = Lasso(alpha=0.0).fit(X_train, y_train)
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(


MAE: 742.3775742231419
MSE: 1348616.2763487475
RMSE: 1161.2993913495122
MAPE: 0.619532952552088
R^2: 0.9176947879258784


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.717e+10, tolerance: 6.817e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(


array([ 1.13956686e+04, -6.55234005e+01, -2.55279834e+01, -1.06397568e+03,
       -1.19002172e+00, -3.32938416e+01, -7.79701955e+02, -1.67789351e+02,
        8.65934394e+01,  1.39991181e+01, -3.20631241e+01,  9.96955843e+02,
        7.86132513e+02,  7.09482070e+02,  5.05149156e+02,  9.12782859e+00,
       -4.76800209e+02, -1.36257801e+03, -4.25861277e+03,  9.63237107e+02,
       -6.92114768e+02, -1.66383488e+03,  2.31133999e+02, -9.33219540e+01,
        6.48048467e+02,  5.86266108e+02])

In [ ]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import numpy as np
parameters = {'alpha': np.arange(0, 1, 0.1)}
ridge_optimal = GridSearchCV(Ridge(), parameters).fit(X_train, y_train)
ridge_optimal.best_params_

ridge = Ridge(alpha=ridge_optimal.best_params_["alpha"]).fit(X_train, y_train)
y_pred = ridge.predict(X_test)
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
print(f'R^2: {ridge.score(X_test, y_test)}')
ridge.coef_

MAE: 742.4628104119587
MSE: 1348528.2597189276
RMSE: 1161.261494978167
MAPE: 0.6195558913841087
R^2: 0.9177001595260218


array([ 1.13872281e+04, -6.53826933e+01, -2.55191708e+01, -1.06053714e+03,
       -1.15546094e+00, -3.34153411e+01, -6.04050699e+02,  7.99836883e+00,
        2.62426641e+02,  1.89824834e+02,  1.43800855e+02,  8.29961032e+02,
        6.19175504e+02,  5.42493863e+02,  3.38243810e+02, -1.57639582e+02,
       -6.43370436e+02, -1.52886419e+03, -3.72167285e+03,  1.49773617e+03,
       -1.57585891e+02, -1.12906729e+03,  7.65672235e+02,  4.41269436e+02,
        1.18273995e+03,  1.12090824e+03])

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

p = PolynomialFeatures(2)
X_train_p=p.fit_transform(X_train)
X_test_p=p.fit_transform(X_test)

lr_p=LinearRegression().fit(X_train_p, y_train)
y_pred=lr_p.predict(X_test_p)

print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {mean_absolute_percentage_error(y_test, y_pred)}')
print(f'R^2: {lr_p.score(X_test_p, y_test)}')
lr_p.coef_

MAE: 409.81783450476365
MSE: 483433.5941309683
RMSE: 695.2938904743578
MAPE: 0.15809011062097178
R^2: 0.9704963486007825


array([ 1.93619194e+08, -1.17225748e+12, -2.83559194e+12, -1.16525803e+12,
        6.50338209e+11,  7.18552022e+11, -2.29037369e+11,  8.87092976e+10,
        4.30598478e+10, -2.66661527e+10, -1.03485091e+10,  6.33662387e+10,
        5.79686227e+10,  3.55151802e+10,  1.01860668e+11, -2.81919663e+10,
       -2.56728188e+09,  1.25171837e+10,  2.27294017e+09, -7.46055156e+10,
        1.32242972e+10,  2.75705166e+10, -5.69102970e+10,  9.63730406e+10,
       -4.72075390e+07,  1.74766851e+10,  3.32199397e+09, -1.22972851e+03,
        4.14008060e+00,  3.86771779e+01, -5.26439617e+03,  5.48131147e+03,
        2.43696572e+03,  5.41667030e+11,  5.41667030e+11,  5.41667032e+11,
        5.41667032e+11,  5.41667031e+11,  3.31224719e+11,  3.31224720e+11,
        3.31224719e+11,  3.31224719e+11,  3.31224719e+11,  3.31224718e+11,
        3.31224717e+11,  2.99365716e+11,  2.99365726e+11,  2.99365725e+11,
        2.99365723e+11,  2.99365726e+11,  2.99365726e+11,  2.99365728e+11,
        2.99365728e+11, -

In [ ]:
lasso_p = Lasso(alpha = 0.0).fit(X_train_p, y_train)
y_pred = lasso_p.predict(X_test_p)

print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {mean_absolute_percentage_error(y_test, y_pred)}')
print(f'R^2: {lasso_p.score(X_test_p, y_test)}')
lasso_p.coef_

<ipython-input-93-f8db8a15fb6b>:1: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  lasso_p = Lasso(alpha = 0.0).fit(X_train_p, y_train)
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(


MAE: 415.5006317282019
MSE: 504085.7379740339
RMSE: 709.9899562487021
MAPE: 0.16198261174583567
R^2: 0.969235961114291


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.031e+10, tolerance: 6.817e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(


array([ 0.00000000e+00,  7.84246611e+03, -1.04092951e+02, -4.74364423e+01,
       -1.05013084e+03,  8.46284555e+01,  1.77765529e+02, -1.14479919e+03,
       -2.46411478e+02, -1.91051586e+02,  1.91768418e+02, -8.97092868e+01,
        5.25558616e+01, -5.38449310e+00,  2.13564621e+02,  3.46030213e+02,
       -1.92040949e+01, -1.14026986e+02, -6.97227595e+02, -2.51194789e+03,
        4.17836422e+02, -2.49580244e+02, -6.50792887e+02,  1.39882460e+02,
        2.00269009e+01, -8.71109217e+00,  2.69218568e+02,  2.71705085e+02,
        2.10179654e+01,  4.92567532e+00,  7.51414711e+02,  1.80977698e+02,
       -9.82176759e+01, -5.26365117e+03, -4.60731225e+03, -3.14151018e+03,
       -3.59093727e+03, -3.26596226e+03,  3.55620851e+02,  1.01920949e+03,
        2.78515755e+02, -5.10130525e+02, -1.58201868e+03, -2.09968930e+03,
       -3.73834678e+03, -9.87207371e+03,  2.45161890e+03, -5.93419517e+02,
       -3.71393806e+03,  9.20057435e+02,  4.05926320e+02,  2.39199162e+03,
        2.65198256e+03, -

In [ ]:
ridge_p_optimal = RandomizedSearchCV(Ridge(), parameters).fit(X_train_p, y_train)
print(ridge_p_optimal.best_params_)

ridge_p = Ridge(alpha = ridge_p_optimal.best_params_["alpha"]).fit(X_train_p, y_train)
y_pred = ridge_p.predict(X_test_p)

print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {mean_absolute_percentage_error(y_test, y_pred)}')
print(f'R^2: {ridge_p.score(X_test_p, y_test)}')
ridge_p.coef_

{'alpha': 0.0}
MAE: 410.0733091745458
MSE: 483171.3568259845
RMSE: 695.1052847058382
MAPE: 0.15833224073586866
R^2: 0.9705123527803101


array([ 4.30718418e+13,  2.53097382e+12, -2.54372234e+13, -6.91755215e+13,
       -7.22738313e+11, -8.06069833e+13, -4.37626925e+13, -2.03621383e+14,
       -3.44430206e+13, -2.02167516e+14,  1.29539671e+14, -2.11303593e+14,
       -1.98471065e+12,  8.65806947e+13,  5.24171940e+13,  7.73361298e+13,
        2.70780831e+14,  1.62771726e+14,  1.34402569e+14,  1.34921442e+14,
       -1.34359338e+14,  1.64761465e+14,  2.26299010e+13,  3.57878369e+13,
        1.00617488e+14, -6.74241190e+13,  2.38712087e+12, -1.22736840e+03,
        5.18753951e+00,  3.84847842e+01, -5.26511816e+03,  5.48257977e+03,
        2.43963573e+03, -3.44984625e+13, -3.44984625e+13, -3.44984625e+13,
       -3.44984625e+13, -3.44984625e+13, -1.08271216e+13, -1.08271216e+13,
       -1.08271216e+13, -1.08271216e+13, -1.08271216e+13, -1.08271216e+13,
       -1.08271216e+13,  4.27946102e+13,  4.27946102e+13,  4.27946102e+13,
        4.27946102e+13,  4.27946102e+13,  4.27946102e+13,  4.27946102e+13,
        4.27946102e+13, -

Собственная реализация

Класс линейной регрессии

In [ ]:
class MyLR:
    def __init__( self, learning_rate = 0.0001, iterations = 1000) :
        self.learning_rate = learning_rate
        self.iterations = iterations

    def transform_(self, x):
        return np.concatenate((np.ones((len(x), 1)), x), axis = 1)

    def loss_func(self, x, y, w):
        return sum((y - np.dot(x, w)) ** 2)/x.shape[0]

    def fit(self, x, y):
        dist = np.inf
        eps = 1e-20
        X = self.transform_(x)

        w = np.zeros(X.shape[1])
        iter = 0

        while iter <= self.iterations:
            loss = self.loss_func(X, y, w)
            w = w - self.learning_rate * 2 * np.dot(X.T, np.dot(X, w) - y) /X.shape[0]
            dist = np.abs(loss - self.loss_func(X, y, w))
            iter += 1

            if(dist <= eps):
                break
        print(iter)

        self.w = w
        return self


    def predict(self, x):
        return np.dot(self.transform_(x), self.w)

Регуляризация L2

In [ ]:
class MyRidge:
    def __init__( self, learning_rate, iterations, alpha ) :
        self.learning_rate = learning_rate
        self.iterations = iterations
        self.alpha = alpha

    def transform_(self, x):
        return np.concatenate((np.ones((len(x), 1)), x), axis = 1)

    def loss_func(self, x, y, w):
        return sum(y - np.dot(x, w)) ** 2  + self.alpha * (np.matmul(w, w))/X.shape[0]

    def fit(self, x, y):
        dist = np.inf
        eps = 1e-20
        X = self.transform_(x)

        w = np.zeros(X.shape[1])
        iter = 0

        while iter <= self.iterations:
            loss = self.loss_func(X, y, w)
            w = w - ((self.learning_rate * 2 * np.dot(X.T, np.dot(X, w) - y)) + ( 2 * self.alpha * w ))/X.shape[0]
            dist = np.abs(loss - self.loss_func(X, y, w))
            iter += 1

            if(dist <= eps):
                break
        print(iter)
        self.w = w
        return self


    def predict(self, x):
        return np.dot(self.transform_(x), self.w)

Метрики

In [ ]:
class Metrics:
    def  mean_absolute_error(y_test, y_pred):
        y_true, predictions = np.array(y_test), np.array(y_pred)
        return float(np.mean(np.abs(y_true-predictions)))
    def mean_squared_error(y_test, y_pred):
        y_true, predictions = np.array(y_test), np.array(y_pred)
        return float(np.mean((y_true-predictions)**2))
    def root_mean_squared_error(y_test, y_pred):
        return float(np.sqrt(Metrics.mean_squared_error(y_test, y_pred)))
    def mean_absolute_percentage_error(y_test, y_pred):
        y_true, predictions = np.array(y_test), np.array(y_pred)
        return float(np.mean(np.abs((y_true-predictions)/y_true)))
    def r_2_score( y_test, y_pred):
        y_true, predictions = np.array(y_test), np.array(y_pred)
        mean_value = np.mean(y_test)
        return float(1 - np.sum((y_true - predictions)**2)/ np.sum((y_true - mean_value)**2))

In [ ]:
y = data["price"]
X = data.drop(["price"], axis=1)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler

standardScaler = StandardScaler()
standardScaler.fit(X_train)
X_train_std = pd.DataFrame(standardScaler.transform(X_train), columns=X.columns)
X_test_std = pd.DataFrame(standardScaler.transform(X_test), columns=X.columns)
X_train_std.describe()

carat         depth         table             x             y  \
count  4.315200e+04  4.315200e+04  4.315200e+04  4.315200e+04  4.315200e+04   
mean  -1.325517e-16  1.901663e-15  1.503926e-15 -4.997444e-16 -2.465790e-16   
std    1.000012e+00  1.000012e+00  1.000012e+00  1.000012e+00  1.000012e+00   
min   -1.261322e+00 -1.316634e+01 -6.047996e+00 -5.111190e+00 -4.992200e+00   
25%   -8.384953e-01 -5.232456e-01 -6.547092e-01 -9.086841e-01 -8.815390e-01   
50%   -2.042551e-01  3.866977e-02 -2.052687e-01 -3.427722e-02 -2.805428e-02   
75%    5.145505e-01  5.303457e-01  6.936124e-01  7.241369e-01  6.947950e-01   
max    7.829454e+00  1.211985e+01  9.682423e+00  4.016546e+00  4.630397e+01   

                  z      cut_Fair      cut_Good     cut_Ideal   cut_Premium  \
count  4.315200e+04  4.315200e+04  4.315200e+04  4.315200e+04  4.315200e+04   
mean  -2.043436e-16 -6.981603e-17 -1.218487e-17  4.165909e-17  2.832160e-17   
std    1.000012e+00  1.000012e+00  1.000012e+00  1.000012e+00  1.000012e+00   
min   -4.998407e+00 -1.746297e-01 -3.152110e-01 -8.170565e-01 -5.849144e-01   
25%   -8.860212e-01 -1.746297e-01 -3.152110e-01 -8.170565e-01 -5.849144e-01   
50%   -2.397467e-02 -1.746297e-01 -3.152110e-01 -8.170565e-01 -5.849144e-01   
75%    6.967528e-01 -1.746297e-01 -3.152110e-01  1.223906e+00  1.709652e+00   
max    3.994107e+01  5.726404e+00  3.172478e+00  1.223906e+00  1.709652e+00   

       ...       color_I       color_J    clarity_I1    clarity_IF  \
count  ...  4.315200e+04  4.315200e+04  4.315200e+04  4.315200e+04   
mean   ... -1.646604e-18  5.911310e-17 -5.145639e-18  1.267885e-17   
std    ...  1.000012e+00  1.000012e+00  1.000012e+00  1.000012e+00   
min    ... -3.364488e-01 -2.342661e-01 -1.174337e-01 -1.838578e-01   
25%    ... -3.364488e-01 -2.342661e-01 -1.174337e-01 -1.838578e-01   
50%    ... -3.364488e-01 -2.342661e-01 -1.174337e-01 -1.838578e-01   
75%    ... -3.364488e-01 -2.342661e-01 -1.174337e-01 -1.838578e-01   
max    ...  2.972220e+00  4.268651e+00  8.515443e+00  5.438986e+00   

        clarity_SI1   clarity_SI2   clarity_VS1   clarity_VS2  clarity_VVS1  \
count  4.315200e+04  4.315200e+04  4.315200e+04  4.315200e+04  4.315200e+04   
mean   1.564274e-18 -1.481944e-18 -3.062684e-17  6.413524e-17  5.252668e-17   
std    1.000012e+00  1.000012e+00  1.000012e+00  1.000012e+00  1.000012e+00   
min   -5.641832e-01 -4.524269e-01 -4.223036e-01 -5.421017e-01 -2.727054e-01   
25%   -5.641832e-01 -4.524269e-01 -4.223036e-01 -5.421017e-01 -2.727054e-01   
50%   -5.641832e-01 -4.524269e-01 -4.223036e-01 -5.421017e-01 -2.727054e-01   
75%   -5.641832e-01 -4.524269e-01 -4.223036e-01 -5.421017e-01 -2.727054e-01   
max    1.772474e+00  2.210302e+00  2.367965e+00  1.844672e+00  3.666961e+00   

       clarity_VVS2  
count  4.315200e+04  
mean   2.535771e-17  
std    1.000012e+00  
min   -3.233198e-01  
25%   -3.233198e-01  
50%   -3.233198e-01  
75%   -3.233198e-01  
max    3.092913e+00  

[8 rows x 26 columns]

In [ ]:
myLinearRegression = MyLR()
model = myLinearRegression.fit(X_train_std, y_train)
y_pred = myLinearRegression.predict(X_test_std)
print(f'MAE: {Metrics.mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {Metrics.mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {Metrics.root_mean_squared_error(y_test, y_pred)}')
print(f'MAPE: {Metrics.mean_absolute_percentage_error(y_test, y_pred)}')
print(f'R^2: {Metrics.r_2_score(y_test, y_pred):.7f}')

1001
MAE: 3226.1129326581677
MSE: 16240544.921266539
RMSE: 4029.9559453257725
MAPE: 1.4651335729154078
R^2: -0.0194474


In [ ]:
ridge = MyRidge(0.01, 1000, 0.9)
model = ridge.fit(X_train_std, y_train)
y_pred = ridge.predict(X_test_std)
print(f'MAE: {Metrics.mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {Metrics.mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {Metrics.root_mean_squared_error(y_test, y_pred)}')
print(f'MAPE: {Metrics.mean_absolute_percentage_error(y_test, y_pred)}')
print(f'R^2: {Metrics.r_2_score(y_test, y_pred):.7f}')

1001
MAE: 869.186637302818
MSE: 1511411.2395023124
RMSE: 1229.3946638497796
MAPE: 0.4864688647716879
R^2: 0.9051261
